/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.arquitecto.vista;

import javax.swing.BoxLayout;
import org.springframework.stereotype.Component;

/**
 *
 * @author Carlos Daniel
 */

@Component
@org.springframework.context.annotation.Profile("!test")
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        initCustom();
        prepararProyectos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlPrincipal = new javax.swing.JPanel();
        pnlPrincipalCabecera = new javax.swing.JPanel();
        pnlCabeceraFoto = new javax.swing.JPanel();
        btnFoto = new javax.swing.JButton();
        pnlCabeceraArriba = new javax.swing.JPanel();
        txtBienvenido = new javax.swing.JLabel();
        txtNombreArc = new javax.swing.JLabel();
        pnlCabeceraAbajo = new javax.swing.JPanel();
        pnlCabeceraBoton = new javax.swing.JPanel();
        btnNuevoProyecto = new javax.swing.JButton();
        pnlPrincipalCuerpo = new javax.swing.JPanel();
        lblProyectos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelProyectos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlPrincipalCabecera.setLayout(new java.awt.BorderLayout());

        pnlCabeceraFoto.setLayout(new java.awt.GridLayout());
        pnlCabeceraFoto.add(btnFoto);

        pnlPrincipalCabecera.add(pnlCabeceraFoto, java.awt.BorderLayout.WEST);

        pnlCabeceraArriba.setLayout(new java.awt.GridLayout(2, 0));

        txtBienvenido.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        txtBienvenido.setText("Bienvenido, Arquitecto");
        pnlCabeceraArriba.add(txtBienvenido);

        txtNombreArc.setText("Jaime José Campos Obregon");
        txtNombreArc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlCabeceraArriba.add(txtNombreArc);

        pnlPrincipalCabecera.add(pnlCabeceraArriba, java.awt.BorderLayout.CENTER);

        pnlCabeceraAbajo.setLayout(new java.awt.GridLayout(0, 1));

        pnlCabeceraBoton.setLayout(new java.awt.BorderLayout(10, 10));

        btnNuevoProyecto.setText("+ Nuevo Proyecto");
        pnlCabeceraBoton.add(btnNuevoProyecto, java.awt.BorderLayout.WEST);

        pnlCabeceraAbajo.add(pnlCabeceraBoton);

        pnlPrincipalCabecera.add(pnlCabeceraAbajo, java.awt.BorderLayout.PAGE_END);

        PnlPrincipal.add(pnlPrincipalCabecera, java.awt.BorderLayout.NORTH);

        pnlPrincipalCuerpo.setLayout(new java.awt.BorderLayout());

        lblProyectos.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        lblProyectos.setText("Proyectos");
        pnlPrincipalCuerpo.add(lblProyectos, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout panelProyectosLayout = new javax.swing.GroupLayout(panelProyectos);
        panelProyectos.setLayout(panelProyectosLayout);
        panelProyectosLayout.setHorizontalGroup(
            panelProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        panelProyectosLayout.setVerticalGroup(
            panelProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelProyectos);

        pnlPrincipalCuerpo.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        PnlPrincipal.add(pnlPrincipalCuerpo, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlPrincipal;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnNuevoProyecto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProyectos;
    private javax.swing.JPanel panelProyectos;
    private javax.swing.JPanel pnlCabeceraAbajo;
    private javax.swing.JPanel pnlCabeceraArriba;
    private javax.swing.JPanel pnlCabeceraBoton;
    private javax.swing.JPanel pnlCabeceraFoto;
    private javax.swing.JPanel pnlPrincipalCabecera;
    private javax.swing.JPanel pnlPrincipalCuerpo;
    private javax.swing.JLabel txtBienvenido;
    private javax.swing.JLabel txtNombreArc;
    // End of variables declaration//GEN-END:variables

    private void initCustom() {
        cargarIconos();
    }

    private void prepararProyectos() {
        panelProyectos.setLayout(new BoxLayout(panelProyectos, BoxLayout.Y_AXIS));

        panelProyectos.removeAll();

        panelProyectos.add(new ProyectoCard("Casa Moderna", "22/04/2024", "$150,000"));
        panelProyectos.add(new ProyectoCard("Edificio Comercial", "22/04/2024", "$750,000"));
        panelProyectos.add(new ProyectoCard("Renovación Oficina", "10/04/2024", "$85,000"));

        panelProyectos.revalidate();
        panelProyectos.repaint();
    }

    private void cargarIconos() {
        try{
            btnFoto.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/arquitecto.svg", 50, 50));
        }catch(Exception e) {
            System.err.println("No se encontró algún icono: " + e.getMessage());
        }
    }
}
