/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.arquitecto.frontend.vista;

import com.arquitecto.DAO.MaterialDAO;
import com.arquitecto.model.Material;
import com.arquitecto.frontend.dialog.Preeliminares;

import database.database;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

/**
 *
 * @author Carlos Daniel
 */
@Component
@org.springframework.context.annotation.Profile("!test")
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    @Autowired
    private ApplicationContext context;

    //Variable para los botones de agregar/eliminar del dialog 'Preeliminar'
    private boolean[] conceptosAgregados;

    MaterialDAO dao = new MaterialDAO();
    //ID de los conceptos
    List<Integer> id_pre = new ArrayList<>();

    //Arreglo de label para el panel de preeliminares
    private JLabel[] labelsPreeliminares = new JLabel[5];

    public VentanaPrincipal() {
        initComponents();
        initCustom();

        prepararProyectos();
        prepararEventos();
        conceptosAgregados = new boolean[10];

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlInicio = new javax.swing.JPanel();
        pnlPrincipalCuerpo = new javax.swing.JPanel();
        lblProyectos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelProyectos = new javax.swing.JPanel();
        pnlPrincipalCabecera = new javax.swing.JPanel();
        pnlCabeceraFoto = new javax.swing.JPanel();
        btnFoto = new javax.swing.JButton();
        pnlCabeceraArriba = new javax.swing.JPanel();
        txtBienvenido = new javax.swing.JLabel();
        txtNombreArc = new javax.swing.JLabel();
        pnlCabeceraAbajo = new javax.swing.JPanel();
        pnlCabeceraBoton = new javax.swing.JPanel();
        btnNuevoProyecto = new javax.swing.JButton();
        pnlMateriales = new javax.swing.JPanel();
        pnlPrincipalMateriales = new javax.swing.JPanel();
        pnlCabecera = new javax.swing.JPanel();
        txtMateriales = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        pnlTabla = new javax.swing.JPanel();
        pnlTablaCentro = new javax.swing.JPanel();
        tbpMateriales = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCimientos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPolvo = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMuros = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        pnlPreeliminares = new javax.swing.JPanel();
        pnlPreliminaresPrincipal = new javax.swing.JPanel();
        pnlConceptos = new javax.swing.JPanel();
        pnlConceptosTitulo = new javax.swing.JPanel();
        txtTituloConceptos = new javax.swing.JLabel();
        pnlConceptosTipo = new javax.swing.JPanel();
        pnlConceptosBoton = new javax.swing.JPanel();
        btnAgregarConcepto = new javax.swing.JButton();
        pnlInformacion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setLayout(new java.awt.CardLayout());

        pnlInicio.setLayout(new java.awt.GridLayout(1, 0));

        pnlPrincipalCuerpo.setLayout(new java.awt.BorderLayout());

        lblProyectos.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        lblProyectos.setText("Proyectos");
        pnlPrincipalCuerpo.add(lblProyectos, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout panelProyectosLayout = new javax.swing.GroupLayout(panelProyectos);
        panelProyectos.setLayout(panelProyectosLayout);
        panelProyectosLayout.setHorizontalGroup(
            panelProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 867, Short.MAX_VALUE)
        );
        panelProyectosLayout.setVerticalGroup(
            panelProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2721, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelProyectos);

        pnlPrincipalCuerpo.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlPrincipalCabecera.setLayout(new java.awt.BorderLayout());

        pnlCabeceraFoto.setLayout(new java.awt.GridLayout(1, 0));

        btnFoto.addActionListener(this::btnFotoActionPerformed);
        pnlCabeceraFoto.add(btnFoto);

        pnlPrincipalCabecera.add(pnlCabeceraFoto, java.awt.BorderLayout.WEST);

        pnlCabeceraArriba.setLayout(new java.awt.GridLayout(2, 0));

        txtBienvenido.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        txtBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtBienvenido.setText("Bienvenido, Arquitecto");
        pnlCabeceraArriba.add(txtBienvenido);

        txtNombreArc.setText("Jaime José Campos Obregon");
        txtNombreArc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlCabeceraArriba.add(txtNombreArc);

        pnlPrincipalCabecera.add(pnlCabeceraArriba, java.awt.BorderLayout.CENTER);

        pnlCabeceraAbajo.setLayout(new java.awt.GridLayout(0, 1));

        pnlCabeceraBoton.setLayout(new java.awt.BorderLayout(10, 10));

        btnNuevoProyecto.setText("+ Nuevo Proyecto");
        btnNuevoProyecto.addActionListener(this::btnNuevoProyectoActionPerformed);
        pnlCabeceraBoton.add(btnNuevoProyecto, java.awt.BorderLayout.WEST);

        pnlCabeceraAbajo.add(pnlCabeceraBoton);

        pnlPrincipalCabecera.add(pnlCabeceraAbajo, java.awt.BorderLayout.SOUTH);

        pnlPrincipalCuerpo.add(pnlPrincipalCabecera, java.awt.BorderLayout.NORTH);

        pnlInicio.add(pnlPrincipalCuerpo);

        pnlPrincipal.add(pnlInicio, "cardInicio");

        pnlMateriales.setBackground(new java.awt.Color(255, 0, 51));

        pnlPrincipalMateriales.setLayout(new java.awt.BorderLayout());

        pnlCabecera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        txtMateriales.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        txtMateriales.setForeground(new java.awt.Color(255, 255, 255));
        txtMateriales.setText("Materiales");
        pnlCabecera.add(txtMateriales);

        pnlPrincipalMateriales.add(pnlCabecera, java.awt.BorderLayout.NORTH);

        pnlCentro.setLayout(new java.awt.GridLayout(1, 0));

        pnlTabla.setLayout(new java.awt.BorderLayout());

        pnlTablaCentro.setLayout(new java.awt.GridLayout(1, 0));

        tblCimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Materia Prima", "Unidad 1", "P.U", "Title 4", "P.U"
            }
        ));
        jScrollPane2.setViewportView(tblCimientos);

        tbpMateriales.addTab("Cimientos", jScrollPane2);

        tblPolvo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Materia Prima", "Unidad 1", "P.U", "Unidad 2", "P.U"
            }
        ));
        jScrollPane3.setViewportView(tblPolvo);

        tbpMateriales.addTab("Polvo", jScrollPane3);

        tblMuros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Materia Prima", "Unidad 1", "P.U", "Unidad 2", "P.U"
            }
        ));
        jScrollPane4.setViewportView(tblMuros);

        tbpMateriales.addTab("Muros", jScrollPane4);

        pnlTablaCentro.add(tbpMateriales);

        pnlTabla.add(pnlTablaCentro, java.awt.BorderLayout.CENTER);

        pnlBotones.setLayout(new java.awt.BorderLayout());

        btnRegresar.setText("Regresar");
        pnlBotones.add(btnRegresar, java.awt.BorderLayout.WEST);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(this::btnSiguienteActionPerformed);
        pnlBotones.add(btnSiguiente, java.awt.BorderLayout.EAST);

        pnlTabla.add(pnlBotones, java.awt.BorderLayout.SOUTH);

        pnlCentro.add(pnlTabla);

        pnlPrincipalMateriales.add(pnlCentro, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlMaterialesLayout = new javax.swing.GroupLayout(pnlMateriales);
        pnlMateriales.setLayout(pnlMaterialesLayout);
        pnlMaterialesLayout.setHorizontalGroup(
            pnlMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalMateriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMaterialesLayout.setVerticalGroup(
            pnlMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalMateriales, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlMateriales, "cardMateriales");

        pnlPreliminaresPrincipal.setLayout(new java.awt.BorderLayout());

        pnlConceptos.setLayout(new java.awt.BorderLayout());

        pnlConceptosTitulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        txtTituloConceptos.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        txtTituloConceptos.setForeground(new java.awt.Color(255, 255, 255));
        txtTituloConceptos.setText("Preeliminar");
        pnlConceptosTitulo.add(txtTituloConceptos);

        pnlConceptos.add(pnlConceptosTitulo, java.awt.BorderLayout.PAGE_START);

        pnlConceptosTipo.setLayout(new java.awt.GridLayout(5, 1));
        pnlConceptos.add(pnlConceptosTipo, java.awt.BorderLayout.CENTER);

        pnlConceptosBoton.setLayout(new java.awt.BorderLayout());

        btnAgregarConcepto.setText("+ Agregar Concepto");
        btnAgregarConcepto.addActionListener(this::btnAgregarConceptoActionPerformed);
        pnlConceptosBoton.add(btnAgregarConcepto, java.awt.BorderLayout.PAGE_START);

        pnlConceptos.add(pnlConceptosBoton, java.awt.BorderLayout.SOUTH);

        pnlPreliminaresPrincipal.add(pnlConceptos, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout pnlInformacionLayout = new javax.swing.GroupLayout(pnlInformacion);
        pnlInformacion.setLayout(pnlInformacionLayout);
        pnlInformacionLayout.setHorizontalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        pnlInformacionLayout.setVerticalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        pnlPreliminaresPrincipal.add(pnlInformacion, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlPreeliminaresLayout = new javax.swing.GroupLayout(pnlPreeliminares);
        pnlPreeliminares.setLayout(pnlPreeliminaresLayout);
        pnlPreeliminaresLayout.setHorizontalGroup(
            pnlPreeliminaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPreliminaresPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPreeliminaresLayout.setVerticalGroup(
            pnlPreeliminaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPreliminaresPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlPreeliminares, "cardPreeliminares");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnNuevoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProyectoActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblCimientos.getModel();
        PrepararTabla(modelo, dao.listarCategoria("Cimientos"));
        System.out.println("Hola putas");
    }//GEN-LAST:event_btnNuevoProyectoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAgregarConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarConceptoActionPerformed

        Preeliminares dialog = context.getBean(Preeliminares.class);
        dialog.init(this, conceptosAgregados); // ✅ pasas los parámetros aquí
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

    }//GEN-LAST:event_btnAgregarConceptoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarConcepto;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnNuevoProyecto;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblProyectos;
    private javax.swing.JPanel panelProyectos;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlCabeceraAbajo;
    private javax.swing.JPanel pnlCabeceraArriba;
    private javax.swing.JPanel pnlCabeceraBoton;
    private javax.swing.JPanel pnlCabeceraFoto;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlConceptos;
    private javax.swing.JPanel pnlConceptosBoton;
    private javax.swing.JPanel pnlConceptosTipo;
    private javax.swing.JPanel pnlConceptosTitulo;
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlMateriales;
    private javax.swing.JPanel pnlPreeliminares;
    private javax.swing.JPanel pnlPreliminaresPrincipal;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlPrincipalCabecera;
    private javax.swing.JPanel pnlPrincipalCuerpo;
    private javax.swing.JPanel pnlPrincipalMateriales;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JPanel pnlTablaCentro;
    private javax.swing.JTable tblCimientos;
    private javax.swing.JTable tblMuros;
    private javax.swing.JTable tblPolvo;
    private javax.swing.JTabbedPane tbpMateriales;
    private javax.swing.JLabel txtBienvenido;
    private javax.swing.JLabel txtMateriales;
    private javax.swing.JLabel txtNombreArc;
    private javax.swing.JLabel txtTituloConceptos;
    // End of variables declaration//GEN-END:variables

    private void initCustom() {
        cargarIconos();
        prepararPaneles();
        database.inicializarEstructura();

    }

    private void prepararPaneles() {

        CardLayout cardLayout = (CardLayout) pnlPrincipal.getLayout();

        btnNuevoProyecto.addActionListener(e -> {

            cardLayout.show(pnlPrincipal, "cardMateriales");
        });
        btnSiguiente.addActionListener(e -> {

            cardLayout.show(pnlPrincipal, "cardPreeliminares");
        });
        btnRegresar.addActionListener(e -> {

            cardLayout.show(pnlPrincipal, "cardInicio");
        });

    }

    private void prepararEventos() {

        DefaultTableModel modeloCim = (DefaultTableModel) tblCimientos.getModel();
        DefaultTableModel modeloPol = (DefaultTableModel) tblPolvo.getModel();
        DefaultTableModel modeloMur = (DefaultTableModel) tblMuros.getModel();

        tbpMateriales.addChangeListener(e -> {

            int index = tbpMateriales.getSelectedIndex();

            switch (index) {
                case 0:
                    PrepararTabla(modeloCim, dao.listarCategoria("Cimientos"));
                    break;
                case 1:
                    PrepararTabla(modeloPol, dao.listarCategoria("Polvo"));
                    break;
                case 2:
                    PrepararTabla(modeloMur, dao.listarCategoria("Muros"));
                    break;
                default:
                    break;
            }

        });

    }

    private void prepararProyectos() {
        panelProyectos.setLayout(new BoxLayout(panelProyectos, BoxLayout.Y_AXIS));

        panelProyectos.removeAll();

        panelProyectos.add(new ProyectoCard("Casa Moderna", "22/04/2024", "$150,000"));
        panelProyectos.add(new ProyectoCard("Edificio Comercial", "22/04/2024", "$750,000"));
        panelProyectos.add(new ProyectoCard("Renovación Oficina", "10/04/2024", "$85,000"));

        panelProyectos.revalidate();
        panelProyectos.repaint();

    }

    private void cargarIconos() {
        try {
            btnFoto.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/arquitecto.svg", 50, 50));
        } catch (Exception e) {
            System.err.println("No se encontró algún icono: " + e.getMessage());
        }
    }

    public void PrepararTabla(DefaultTableModel tabla, List<Material> lista) {
        tabla.setRowCount(0);
        for (Material e : lista) {
            Object[] fila = {
                e.getNombre(),
                e.getUnidad1(),
                e.getPu(),
                e.getUnidad2(),
                e.getPu2()
            };
            tabla.addRow(fila);
        }
    }

    public void agregarConceptos(int id) {

        System.out.println("Se llamo a la funcion");
        switch (id) {
            case 0:
                labelsPreeliminares[id] = new JLabel();
                labelsPreeliminares[id].setText("1.1.-Excavacion");
                pnlConceptosTipo.add(labelsPreeliminares[id]);
                pnlConceptosTipo.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosTipo.repaint();

                break;
            case 1:
                labelsPreeliminares[id] = new JLabel();
                labelsPreeliminares[id].setText("1.2 .-Relleno");
                pnlConceptosTipo.add(labelsPreeliminares[id]);
                pnlConceptosTipo.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosTipo.repaint();

                break;
            case 2:
                labelsPreeliminares[id] = new JLabel();
                labelsPreeliminares[id].setText("1.3 .-Planta");
                pnlConceptosTipo.add(labelsPreeliminares[id]);
                pnlConceptosTipo.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosTipo.repaint();

                break;
            case 3:
                labelsPreeliminares[id] = new JLabel();
                labelsPreeliminares[id].setText("1.4 .-Locura");
                pnlConceptosTipo.add(labelsPreeliminares[id]);
                pnlConceptosTipo.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosTipo.repaint();
                break;
            case 4:
                labelsPreeliminares[id] = new JLabel();
                labelsPreeliminares[id].setText("1.5.-Pole ahi un ladrillo");
                pnlConceptosTipo.add(labelsPreeliminares[id]);
                pnlConceptosTipo.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosTipo.repaint();

                break;
        }

    }

    public void EliminarConceptos(int id) {

        System.out.println("Se llamo a la funcion");
        switch (id) {
            case 0:
                pnlConceptosTipo.remove(labelsPreeliminares[id]);

                pnlConceptosTipo.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosTipo.repaint();

                break;
            case 1:
                pnlConceptosTipo.remove(labelsPreeliminares[id]);

                pnlConceptosTipo.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosTipo.repaint();
                ;

                break;
            case 2:
                pnlConceptosTipo.remove(labelsPreeliminares[id]);

                pnlConceptosTipo.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosTipo.repaint();

                break;
            case 3:
                pnlConceptosTipo.remove(labelsPreeliminares[id]);

                pnlConceptosTipo.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosTipo.repaint();
                break;
            case 4:
                pnlConceptosTipo.remove(labelsPreeliminares[id]);

                pnlConceptosTipo.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosTipo.repaint();

                break;
        }

    }

}
