/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.arquitecto.frontend.vista;

import com.arquitecto.DAO.MaterialDAO;
import com.arquitecto.model.Material;
import com.arquitecto.frontend.dialog.Preeliminares;
import com.arquitecto.frontend.components.BotonPrimario;
import com.arquitecto.frontend.components.PanelFondo;
import com.arquitecto.frontend.components.PanelSemitransparente;
import com.arquitecto.frontend.components.ScrollPanelTransparente;
import com.arquitecto.frontend.components.TablaTransparente;
import com.arquitecto.frontend.components.TabbedPaneTransparente;
import com.arquitecto.frontend.components.BotonSVG;
import database.database;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

/**
 *
 * @author Carlos Daniel
 */
@Component
@org.springframework.context.annotation.Profile("!test")
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    @Autowired
    private ApplicationContext context;

    //Variable para los botones de agregar/eliminar del dialog 'Preeliminar'
    private boolean[] conceptosAgregados;

    MaterialDAO dao = new MaterialDAO();

    ArrayList<Integer> id_panelesPre = new ArrayList<>();

    private JPanel[] panelesPreeliminares = new JPanel[5];

    public VentanaPrincipal() {
        initComponents();
        initCustom();
        

        //prepararProyectos();
        prepararEventos();
        conceptosAgregados = new boolean[10];

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlInicio = new PanelFondo();
        pnlPrincipalCuerpo = new javax.swing.JPanel();
        pnlPrincipalCabecera = new javax.swing.JPanel();
        pnlCabeceraFoto = new javax.swing.JPanel();
        btnFoto = new BotonSVG("arquitecto",100);
        pnlCabeceraArriba = new javax.swing.JPanel();
        txtBienvenido = new javax.swing.JLabel();
        txtNombreArc = new javax.swing.JLabel();
        pnlCabeceraAbajo = new javax.swing.JPanel();
        pnlCabeceraBoton = new PanelSemitransparente(150,10);
        btnNuevoProyecto = new BotonPrimario();
        jScrollPane1 = new ScrollPanelTransparente();
        panelProyectos = new javax.swing.JPanel();
        lblProyectostTitulo = new javax.swing.JLabel();
        pnlMateriales = new PanelFondo();
        pnlPrincipalMateriales = new javax.swing.JPanel();
        pnlCabecera = new javax.swing.JPanel();
        txtMateriales = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        pnlTabla = new PanelSemitransparente(50,20);
        pnlTablaCentro = new PanelSemitransparente(100,20);
        tbpMateriales = new TabbedPaneTransparente();
        javax.swing.JScrollPane jScrollPane2 = new ScrollPanelTransparente();
        tblCimientos = new TablaTransparente();
        jScrollPane3 = new ScrollPanelTransparente();
        tblPolvo = new TablaTransparente();
        jScrollPane4 = new ScrollPanelTransparente();
        tblMuros = new TablaTransparente();
        pnlBotones = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnSiguiente = new BotonPrimario("Siguiente ->");
        pnlPreeliminares = new PanelFondo();
        pnlPreliminaresPrincipal = new javax.swing.JPanel();
        pnlConceptos = new PanelSemitransparente( 100,20);
        pnlConceptosTitulo = new javax.swing.JPanel();
        txtTituloConceptos = new javax.swing.JLabel();
        pnlConceptosCuerpo = new javax.swing.JPanel();
        pnlConceptosAgregar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarConcepto = new BotonPrimario();
        pnlConceptosBoton = new javax.swing.JPanel();
        btnRegresarMateriales = new javax.swing.JButton();
        pnlInformacion = new javax.swing.JPanel();
        pnlPre1 = new javax.swing.JPanel();
        ScrollPre1 = new javax.swing.JScrollPane();
        pnlCuerpoPre1 = new javax.swing.JPanel();
        pnlCuerpoCabPre1 = new javax.swing.JPanel();
        pnlCuerpoCabTit = new javax.swing.JPanel();
        lblConceptoPre = new javax.swing.JLabel();
        lblConceptoPre1 = new javax.swing.JLabel();
        pnlCuerpoCabDesc = new javax.swing.JPanel();
        lblUnidadDes = new javax.swing.JLabel();
        lblUnidadRes = new javax.swing.JLabel();
        lblCantidadDes = new javax.swing.JLabel();
        lblCantidadRes = new javax.swing.JLabel();
        lblPresioDes = new javax.swing.JLabel();
        lblPrecioRes = new javax.swing.JLabel();
        lblUnidadDes6 = new javax.swing.JLabel();
        lblTotalRes = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnlCuerpoCentPre1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblMaterialPre = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlCuerpoBajoPre1 = new javax.swing.JPanel();
        javax.swing.JButton btnGuardar1_1 = new BotonPrimario();
        pnlPre2 = new javax.swing.JPanel();
        pnlPre3 = new javax.swing.JPanel();
        pnlPre4 = new javax.swing.JPanel();
        pnlPre5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setLayout(new java.awt.CardLayout());

        pnlInicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
        pnlInicio.setLayout(new java.awt.GridLayout(1, 0));

        pnlPrincipalCuerpo.setOpaque(false);
        pnlPrincipalCuerpo.setLayout(new java.awt.BorderLayout(0, 20));

        pnlPrincipalCabecera.setOpaque(false);
        pnlPrincipalCabecera.setLayout(new java.awt.BorderLayout(15, 30));

        pnlCabeceraFoto.setOpaque(false);
        pnlCabeceraFoto.setLayout(new java.awt.GridLayout(1, 0));

        btnFoto.addActionListener(this::btnFotoActionPerformed);
        pnlCabeceraFoto.add(btnFoto);

        pnlPrincipalCabecera.add(pnlCabeceraFoto, java.awt.BorderLayout.WEST);

        pnlCabeceraArriba.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 1, 1, 1));
        pnlCabeceraArriba.setOpaque(false);
        pnlCabeceraArriba.setLayout(new javax.swing.BoxLayout(pnlCabeceraArriba, javax.swing.BoxLayout.Y_AXIS));

        txtBienvenido.setFont(new java.awt.Font("Modern No. 20", 1, 48)); // NOI18N
        txtBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtBienvenido.setText("Bienvenido, Arquitecto");
        pnlCabeceraArriba.add(txtBienvenido);

        txtNombreArc.setText("Jaime José Campos Obregon");
        txtNombreArc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlCabeceraArriba.add(txtNombreArc);

        pnlPrincipalCabecera.add(pnlCabeceraArriba, java.awt.BorderLayout.CENTER);

        pnlCabeceraAbajo.setOpaque(false);
        pnlCabeceraAbajo.setLayout(new java.awt.GridLayout(0, 1));

        pnlCabeceraBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        pnlCabeceraBoton.setOpaque(false);
        pnlCabeceraBoton.setLayout(new java.awt.BorderLayout(10, 10));

        btnNuevoProyecto.setText("+ Nuevo Proyecto");
        btnNuevoProyecto.addActionListener(this::btnNuevoProyectoActionPerformed);
        pnlCabeceraBoton.add(btnNuevoProyecto, java.awt.BorderLayout.WEST);

        pnlCabeceraAbajo.add(pnlCabeceraBoton);

        pnlPrincipalCabecera.add(pnlCabeceraAbajo, java.awt.BorderLayout.SOUTH);

        pnlPrincipalCuerpo.add(pnlPrincipalCabecera, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        panelProyectos.setOpaque(false);
        panelProyectos.setPreferredSize(new java.awt.Dimension(0, 0));
        panelProyectos.setLayout(new java.awt.BorderLayout());

        lblProyectostTitulo.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        lblProyectostTitulo.setText("Proyectos");
        panelProyectos.add(lblProyectostTitulo, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(panelProyectos);

        pnlPrincipalCuerpo.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlInicio.add(pnlPrincipalCuerpo);

        pnlPrincipal.add(pnlInicio, "cardInicio");

        pnlMateriales.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));

        pnlPrincipalMateriales.setOpaque(false);
        pnlPrincipalMateriales.setLayout(new java.awt.BorderLayout());

        pnlCabecera.setOpaque(false);
        pnlCabecera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        txtMateriales.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        txtMateriales.setForeground(new java.awt.Color(255, 255, 255));
        txtMateriales.setText("Materiales");
        pnlCabecera.add(txtMateriales);

        pnlPrincipalMateriales.add(pnlCabecera, java.awt.BorderLayout.NORTH);

        pnlCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 25, 25, 25));
        pnlCentro.setOpaque(false);
        pnlCentro.setLayout(new java.awt.GridLayout(1, 0));

        pnlTabla.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));
        pnlTabla.setOpaque(false);
        pnlTabla.setLayout(new java.awt.BorderLayout());

        pnlTablaCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));
        pnlTablaCentro.setOpaque(false);
        pnlTablaCentro.setLayout(new java.awt.GridLayout(1, 0));

        tblCimientos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblCimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Materia Prima", "Unidad 1", "P.U", "Title 4", "P.U"
            }
        ));
        jScrollPane2.setViewportView(tblCimientos);

        tbpMateriales.addTab("Cimientos", jScrollPane2);

        tblPolvo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblPolvo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Materia Prima", "Unidad 1", "P.U", "Unidad 2", "P.U"
            }
        ));
        jScrollPane3.setViewportView(tblPolvo);

        tbpMateriales.addTab("Polvo", jScrollPane3);

        tblMuros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblMuros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Materia Prima", "Unidad 1", "P.U", "Unidad 2", "P.U"
            }
        ));
        jScrollPane4.setViewportView(tblMuros);

        tbpMateriales.addTab("Muros", jScrollPane4);

        pnlTablaCentro.add(tbpMateriales);

        pnlTabla.add(pnlTablaCentro, java.awt.BorderLayout.CENTER);

        pnlBotones.setOpaque(false);
        pnlBotones.setLayout(new java.awt.BorderLayout());

        btnRegresar.setText("Regresar");
        pnlBotones.add(btnRegresar, java.awt.BorderLayout.WEST);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(this::btnSiguienteActionPerformed);
        pnlBotones.add(btnSiguiente, java.awt.BorderLayout.EAST);

        pnlTabla.add(pnlBotones, java.awt.BorderLayout.SOUTH);

        pnlCentro.add(pnlTabla);

        pnlPrincipalMateriales.add(pnlCentro, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlMaterialesLayout = new javax.swing.GroupLayout(pnlMateriales);
        pnlMateriales.setLayout(pnlMaterialesLayout);
        pnlMaterialesLayout.setHorizontalGroup(
            pnlMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalMateriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMaterialesLayout.setVerticalGroup(
            pnlMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalMateriales, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlMateriales, "cardMateriales");

        pnlPreliminaresPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
        pnlPreliminaresPrincipal.setOpaque(false);
        pnlPreliminaresPrincipal.setLayout(new java.awt.BorderLayout(40, 0));

        pnlConceptos.setOpaque(false);
        pnlConceptos.setLayout(new java.awt.BorderLayout());

        pnlConceptosTitulo.setOpaque(false);
        pnlConceptosTitulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        txtTituloConceptos.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        txtTituloConceptos.setForeground(new java.awt.Color(255, 255, 255));
        txtTituloConceptos.setText("Preeliminar");
        pnlConceptosTitulo.add(txtTituloConceptos);

        pnlConceptos.add(pnlConceptosTitulo, java.awt.BorderLayout.NORTH);

        pnlConceptosCuerpo.setOpaque(false);
        pnlConceptosCuerpo.setLayout(new javax.swing.BoxLayout(pnlConceptosCuerpo, javax.swing.BoxLayout.Y_AXIS));

        pnlConceptosAgregar.setOpaque(false);
        pnlConceptosAgregar.setLayout(new javax.swing.BoxLayout(pnlConceptosAgregar, javax.swing.BoxLayout.Y_AXIS));
        pnlConceptosCuerpo.add(pnlConceptosAgregar);

        jPanel1.setOpaque(false);

        btnAgregarConcepto.setText("+ Agregar Concepto");
        btnAgregarConcepto.addActionListener(this::btnAgregarConceptoActionPerformed);
        jPanel1.add(btnAgregarConcepto);

        pnlConceptosCuerpo.add(jPanel1);

        pnlConceptos.add(pnlConceptosCuerpo, java.awt.BorderLayout.CENTER);

        pnlConceptosBoton.setOpaque(false);
        pnlConceptosBoton.setLayout(new java.awt.BorderLayout());

        btnRegresarMateriales.setText("<- Regresar");
        btnRegresarMateriales.addActionListener(this::btnRegresarMaterialesActionPerformed);
        pnlConceptosBoton.add(btnRegresarMateriales, java.awt.BorderLayout.PAGE_START);

        pnlConceptos.add(pnlConceptosBoton, java.awt.BorderLayout.SOUTH);

        pnlPreliminaresPrincipal.add(pnlConceptos, java.awt.BorderLayout.WEST);

        pnlInformacion.setOpaque(false);
        pnlInformacion.setLayout(new java.awt.CardLayout());

        pnlPre1.setLayout(new java.awt.GridLayout(1, 0));

        pnlCuerpoPre1.setForeground(new java.awt.Color(0, 102, 51));
        pnlCuerpoPre1.setOpaque(false);
        pnlCuerpoPre1.setLayout(new java.awt.BorderLayout());

        pnlCuerpoCabPre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlCuerpoCabPre1.setOpaque(false);
        pnlCuerpoCabPre1.setLayout(new java.awt.BorderLayout());

        pnlCuerpoCabTit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlCuerpoCabTit.setLayout(new java.awt.BorderLayout());

        lblConceptoPre.setText("CLAVE");
        pnlCuerpoCabTit.add(lblConceptoPre, java.awt.BorderLayout.NORTH);

        lblConceptoPre1.setText("1.1");
        pnlCuerpoCabTit.add(lblConceptoPre1, java.awt.BorderLayout.PAGE_END);

        pnlCuerpoCabPre1.add(pnlCuerpoCabTit, java.awt.BorderLayout.WEST);

        pnlCuerpoCabDesc.setLayout(new java.awt.GridLayout(4, 2));

        lblUnidadDes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUnidadDes.setText("UNIDAD:");
        pnlCuerpoCabDesc.add(lblUnidadDes);

        lblUnidadRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUnidadRes.setText("m3");
        pnlCuerpoCabDesc.add(lblUnidadRes);

        lblCantidadDes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCantidadDes.setText("CANTIDAD");
        pnlCuerpoCabDesc.add(lblCantidadDes);

        lblCantidadRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantidadRes.setText("1.00");
        pnlCuerpoCabDesc.add(lblCantidadRes);

        lblPresioDes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPresioDes.setText("PRECIO UNITARIO:");
        pnlCuerpoCabDesc.add(lblPresioDes);

        lblPrecioRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecioRes.setText("$132.20");
        pnlCuerpoCabDesc.add(lblPrecioRes);

        lblUnidadDes6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUnidadDes6.setText("TOTAL");
        pnlCuerpoCabDesc.add(lblUnidadDes6);

        lblTotalRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalRes.setText("$132.20");
        pnlCuerpoCabDesc.add(lblTotalRes);

        pnlCuerpoCabPre1.add(pnlCuerpoCabDesc, java.awt.BorderLayout.EAST);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("DESPALME DE CAPA VEGETAL DE 10 A 15 CMS DE ESPESOR POR MEDIOS MECANICOS. INCLUYE,\nACARREO DENTRO DE LA OBRA, EQUIPO, HERRAMIENTA MENOR Y MANO DE OBRA.\n");
        jTextArea1.setEnabled(false);
        jScrollPane5.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleName("");
        jTextArea1.getAccessibleContext().setAccessibleDescription("");

        pnlCuerpoCabPre1.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        pnlCuerpoPre1.add(pnlCuerpoCabPre1, java.awt.BorderLayout.NORTH);

        pnlCuerpoCentPre1.setOpaque(false);
        pnlCuerpoCentPre1.setLayout(new java.awt.GridLayout(1, 0));

        tblMaterialPre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Descripcion", "Unidad", "Cantidad", "Costo Unitario", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblMaterialPre);

        jTabbedPane1.addTab("Material", jScrollPane6);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Descripcion", "Unidad", "Cantidad", "Costo Unitario", "Total"
            }
        ));
        jScrollPane7.setViewportView(jTable2);

        jTabbedPane1.addTab("Mano de obra", jScrollPane7);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Descripcion", "Unidad", "Cantidad", "Costo Unitario", "Total"
            }
        ));
        jScrollPane8.setViewportView(jTable3);

        jTabbedPane1.addTab("Herramienta", jScrollPane8);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Descripcion", "Unidad", "Cantidad", "Costo Unitario", "Total"
            }
        ));
        jScrollPane9.setViewportView(jTable1);

        jTabbedPane1.addTab("Equipo", jScrollPane9);

        pnlCuerpoCentPre1.add(jTabbedPane1);

        pnlCuerpoPre1.add(pnlCuerpoCentPre1, java.awt.BorderLayout.CENTER);

        pnlCuerpoBajoPre1.setOpaque(false);
        pnlCuerpoBajoPre1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnGuardar1_1.setText("Guardar");
        pnlCuerpoBajoPre1.add(btnGuardar1_1);

        pnlCuerpoPre1.add(pnlCuerpoBajoPre1, java.awt.BorderLayout.PAGE_END);

        ScrollPre1.setViewportView(pnlCuerpoPre1);

        pnlPre1.add(ScrollPre1);

        pnlInformacion.add(pnlPre1, "cardPre1");

        pnlPre2.setBackground(new java.awt.Color(102, 255, 51));
        pnlPre2.setOpaque(false);

        javax.swing.GroupLayout pnlPre2Layout = new javax.swing.GroupLayout(pnlPre2);
        pnlPre2.setLayout(pnlPre2Layout);
        pnlPre2Layout.setHorizontalGroup(
            pnlPre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        pnlPre2Layout.setVerticalGroup(
            pnlPre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        pnlInformacion.add(pnlPre2, "cardPre2");

        pnlPre3.setBackground(new java.awt.Color(0, 51, 204));
        pnlPre3.setOpaque(false);

        javax.swing.GroupLayout pnlPre3Layout = new javax.swing.GroupLayout(pnlPre3);
        pnlPre3.setLayout(pnlPre3Layout);
        pnlPre3Layout.setHorizontalGroup(
            pnlPre3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        pnlPre3Layout.setVerticalGroup(
            pnlPre3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        pnlInformacion.add(pnlPre3, "cardPre3");

        pnlPre4.setBackground(new java.awt.Color(102, 102, 102));
        pnlPre4.setOpaque(false);

        javax.swing.GroupLayout pnlPre4Layout = new javax.swing.GroupLayout(pnlPre4);
        pnlPre4.setLayout(pnlPre4Layout);
        pnlPre4Layout.setHorizontalGroup(
            pnlPre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        pnlPre4Layout.setVerticalGroup(
            pnlPre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        pnlInformacion.add(pnlPre4, "cardPre4");

        pnlPre5.setBackground(new java.awt.Color(0, 102, 102));
        pnlPre5.setOpaque(false);

        javax.swing.GroupLayout pnlPre5Layout = new javax.swing.GroupLayout(pnlPre5);
        pnlPre5.setLayout(pnlPre5Layout);
        pnlPre5Layout.setHorizontalGroup(
            pnlPre5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        pnlPre5Layout.setVerticalGroup(
            pnlPre5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        pnlInformacion.add(pnlPre5, "cardPre5");

        pnlPreliminaresPrincipal.add(pnlInformacion, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlPreeliminaresLayout = new javax.swing.GroupLayout(pnlPreeliminares);
        pnlPreeliminares.setLayout(pnlPreeliminaresLayout);
        pnlPreeliminaresLayout.setHorizontalGroup(
            pnlPreeliminaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPreliminaresPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPreeliminaresLayout.setVerticalGroup(
            pnlPreeliminaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPreliminaresPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlPreeliminares, "cardPreeliminares");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnNuevoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProyectoActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblCimientos.getModel();
        PrepararTabla(modelo, dao.listarCategoria("Cimientos"));
        System.out.println("Hola putas");
    }//GEN-LAST:event_btnNuevoProyectoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnRegresarMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMaterialesActionPerformed


    }//GEN-LAST:event_btnRegresarMaterialesActionPerformed

    private void btnAgregarConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarConceptoActionPerformed
        Preeliminares dialog = context.getBean(Preeliminares.class);
        dialog.init(this, conceptosAgregados); // ✅ pasas los parámetros aquí
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

    }//GEN-LAST:event_btnAgregarConceptoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPre1;
    private javax.swing.JButton btnAgregarConcepto;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnNuevoProyecto;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresarMateriales;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCantidadDes;
    private javax.swing.JLabel lblCantidadRes;
    private javax.swing.JLabel lblConceptoPre;
    private javax.swing.JLabel lblConceptoPre1;
    private javax.swing.JLabel lblPrecioRes;
    private javax.swing.JLabel lblPresioDes;
    private javax.swing.JLabel lblProyectostTitulo;
    private javax.swing.JLabel lblTotalRes;
    private javax.swing.JLabel lblUnidadDes;
    private javax.swing.JLabel lblUnidadDes6;
    private javax.swing.JLabel lblUnidadRes;
    private javax.swing.JPanel panelProyectos;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlCabeceraAbajo;
    private javax.swing.JPanel pnlCabeceraArriba;
    private javax.swing.JPanel pnlCabeceraBoton;
    private javax.swing.JPanel pnlCabeceraFoto;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlConceptos;
    private javax.swing.JPanel pnlConceptosAgregar;
    private javax.swing.JPanel pnlConceptosBoton;
    private javax.swing.JPanel pnlConceptosCuerpo;
    private javax.swing.JPanel pnlConceptosTitulo;
    private javax.swing.JPanel pnlCuerpoBajoPre1;
    private javax.swing.JPanel pnlCuerpoCabDesc;
    private javax.swing.JPanel pnlCuerpoCabPre1;
    private javax.swing.JPanel pnlCuerpoCabTit;
    private javax.swing.JPanel pnlCuerpoCentPre1;
    private javax.swing.JPanel pnlCuerpoPre1;
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlMateriales;
    private javax.swing.JPanel pnlPre1;
    private javax.swing.JPanel pnlPre2;
    private javax.swing.JPanel pnlPre3;
    private javax.swing.JPanel pnlPre4;
    private javax.swing.JPanel pnlPre5;
    private javax.swing.JPanel pnlPreeliminares;
    private javax.swing.JPanel pnlPreliminaresPrincipal;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlPrincipalCabecera;
    private javax.swing.JPanel pnlPrincipalCuerpo;
    private javax.swing.JPanel pnlPrincipalMateriales;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JPanel pnlTablaCentro;
    private javax.swing.JTable tblCimientos;
    private javax.swing.JTable tblMaterialPre;
    private javax.swing.JTable tblMuros;
    private javax.swing.JTable tblPolvo;
    private javax.swing.JTabbedPane tbpMateriales;
    private javax.swing.JLabel txtBienvenido;
    private javax.swing.JLabel txtMateriales;
    private javax.swing.JLabel txtNombreArc;
    private javax.swing.JLabel txtTituloConceptos;
    // End of variables declaration//GEN-END:variables

    private void initCustom() {

        prepararPaneles();
        database.inicializarEstructura();

    }

    private void prepararPaneles() {

        CardLayout cardLayout = (CardLayout) pnlPrincipal.getLayout();

        btnNuevoProyecto.addActionListener(e -> {

            cardLayout.show(pnlPrincipal, "cardMateriales");
        });
        btnSiguiente.addActionListener(e -> {

            cardLayout.show(pnlPrincipal, "cardPreeliminares");
        });
        btnRegresar.addActionListener(e -> {

            cardLayout.show(pnlPrincipal, "cardInicio");
        });
        
        btnRegresarMateriales.addActionListener(e -> {

            cardLayout.show(pnlPrincipal, "cardMateriales");
        });
        

        
        
        

        
        

    }

    private void prepararEventos() {

        DefaultTableModel modeloCim = (DefaultTableModel) tblCimientos.getModel();
        DefaultTableModel modeloPol = (DefaultTableModel) tblPolvo.getModel();
        DefaultTableModel modeloMur = (DefaultTableModel) tblMuros.getModel();

        tbpMateriales.addChangeListener(e -> {

            int index = tbpMateriales.getSelectedIndex();

            switch (index) {
                case 0:
                    PrepararTabla(modeloCim, dao.listarCategoria("Cimientos"));
                    break;
                case 1:
                    PrepararTabla(modeloPol, dao.listarCategoria("Polvo"));
                    break;
                case 2:
                    PrepararTabla(modeloMur, dao.listarCategoria("Muros"));
                    break;
                default:
                    break;
            }

        });

    }

    private void prepararProyectos() {
        panelProyectos.setLayout(new BoxLayout(panelProyectos, BoxLayout.Y_AXIS));

        panelProyectos.removeAll();

        panelProyectos.add(new ProyectoCard("Casa Moderna", "22/04/2024", "$150,000"));
        panelProyectos.add(new ProyectoCard("Edificio Comercial", "22/04/2024", "$750,000"));
        panelProyectos.add(new ProyectoCard("Renovación Oficina", "10/04/2024", "$85,000"));

        panelProyectos.revalidate();
        panelProyectos.repaint();

    }

   

    public void PrepararTabla(DefaultTableModel tabla, List<Material> lista) {
        tabla.setRowCount(0);
        for (Material e : lista) {
            Object[] fila = {
                e.getNombre(),
                e.getUnidad1(),
                e.getPu(),
                e.getUnidad2(),
                e.getPu2()
            };
            tabla.addRow(fila);
        }
    }

    public void agregarConceptos(int id) {

        //Paneles de Preeliminares
        CardLayout cardLayoutPre = (CardLayout) pnlInformacion.getLayout();
        System.out.println("Se llamo a la funcion");
        switch (id) {
            case 0:

                panelesPreeliminares[id] = new JPanel(new FlowLayout(FlowLayout.LEFT));
                JButton btnPre1 = new JButton("1.1 Acabado");
                panelesPreeliminares[id].add(btnPre1);

                pnlConceptosAgregar.add(panelesPreeliminares[id], BorderLayout.CENTER);
                btnPre1.addActionListener(e -> {

                    cardLayoutPre.show(pnlInformacion, "cardPre1");
                });

                panelesPreeliminares[id].setMaximumSize(
                        new Dimension(Integer.MAX_VALUE,
                                panelesPreeliminares[id].getPreferredSize().height)
                );
                pnlConceptosAgregar.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosAgregar.repaint();
                
                id_panelesPre.add(0);

                break;
            case 1:
                panelesPreeliminares[id] = new JPanel(new FlowLayout(FlowLayout.LEFT));
                JButton btnPre2 = new JButton("1.2 .-Relleno");
                panelesPreeliminares[id].add(btnPre2);
                btnPre2.addActionListener(e -> {

                    cardLayoutPre.show(pnlInformacion, "cardPre2");
                });
                panelesPreeliminares[id].setMaximumSize(
                        new Dimension(Integer.MAX_VALUE,
                                panelesPreeliminares[id].getPreferredSize().height)
                );

                pnlConceptosAgregar.add(panelesPreeliminares[id], BorderLayout.CENTER);
                pnlConceptosAgregar.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosAgregar.repaint();

                id_panelesPre.add(1);
                break;
            case 2:
                panelesPreeliminares[id] = new JPanel(new FlowLayout(FlowLayout.LEFT));
                JButton btnPre3 = new JButton("1.3 .-Excavacion");
                panelesPreeliminares[id].add(btnPre3);
                btnPre3.addActionListener(e -> {

                    cardLayoutPre.show(pnlInformacion, "cardPre3");
                });
                panelesPreeliminares[id].setMaximumSize(
                        new Dimension(Integer.MAX_VALUE,
                                panelesPreeliminares[id].getPreferredSize().height)
                );

                pnlConceptosAgregar.add(panelesPreeliminares[id], BorderLayout.CENTER);
                pnlConceptosAgregar.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosAgregar.repaint();

                id_panelesPre.add(2);
                break;
            case 3:
                panelesPreeliminares[id] = new JPanel(new FlowLayout(FlowLayout.LEFT));
                JButton btnPre4 = new JButton("1.5 .-ahhh");
                panelesPreeliminares[id].add(btnPre4);
                btnPre4.addActionListener(e -> {

                    cardLayoutPre.show(pnlInformacion, "cardPre4");
                });
                panelesPreeliminares[id].setMaximumSize(
                        new Dimension(Integer.MAX_VALUE,
                                panelesPreeliminares[id].getPreferredSize().height)
                );

                pnlConceptosAgregar.add(panelesPreeliminares[id], BorderLayout.CENTER);
                pnlConceptosAgregar.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosAgregar.repaint();
                
                id_panelesPre.add(3);
                break;
            case 4:
                panelesPreeliminares[id] = new JPanel(new FlowLayout(FlowLayout.LEFT));
                JButton btnPre5 = new JButton("1.5 .-ahi va disque un ladrillo");
                panelesPreeliminares[id].add(btnPre5);
                btnPre5.addActionListener(e -> {

                    cardLayoutPre.show(pnlInformacion, "cardPre5");
                });
                panelesPreeliminares[id].setMaximumSize(
                        new Dimension(Integer.MAX_VALUE,
                                panelesPreeliminares[id].getPreferredSize().height)
                );

                pnlConceptosAgregar.add(panelesPreeliminares[id], BorderLayout.CENTER);
                pnlConceptosAgregar.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosAgregar.repaint();

                id_panelesPre.add(4);
                break;
        }

    }

    public void EliminarConceptos(int id) {

        System.out.println("Se llamo a la funcion");
        switch (id) {
            case 0:
                pnlConceptosAgregar.remove(panelesPreeliminares[id]);

                pnlConceptosAgregar.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosAgregar.repaint();

                id_panelesPre.remove(0);
                break;
            case 1:
                pnlConceptosAgregar.remove(panelesPreeliminares[id]);

                pnlConceptosAgregar.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosAgregar.repaint();
                id_panelesPre.remove(1);

                break;
            case 2:
                pnlConceptosAgregar.remove(panelesPreeliminares[id]);

                pnlConceptosAgregar.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosAgregar.repaint();
                id_panelesPre.remove(2);

                break;
            case 3:
                pnlConceptosAgregar.remove(panelesPreeliminares[id]);

                pnlConceptosAgregar.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosAgregar.repaint();
                id_panelesPre.remove(3);
                break;
            case 4:
                pnlConceptosAgregar.remove(panelesPreeliminares[id]);

                pnlConceptosAgregar.revalidate(); // ✅ Refresca el panel visualmente
                pnlConceptosAgregar.repaint();
                id_panelesPre.remove(4);

                break;
        }

    }

}
