/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.arquitecto.vista.Dialog;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author Carlos Daniel
 */
@Component
@Scope("prototype")
public class Preeliminares extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Preeliminares.class.getName());

    /**
     * Creates new form Preeliminares
     */
    @Autowired
    public Preeliminares(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalPreliminares = new javax.swing.JPanel();
        pnlPreliminares = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        pnlConceptosPre = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        btnAgregarPreliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPreliminares.setLayout(new java.awt.BorderLayout());

        pnlTitulo.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        txtTitulo.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setText("Preeliminares");
        jPanel1.add(txtTitulo);

        pnlTitulo.add(jPanel1, java.awt.BorderLayout.NORTH);

        pnlPreliminares.add(pnlTitulo, java.awt.BorderLayout.NORTH);

        pnlConceptosPre.setLayout(new java.awt.GridLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1.1", "Despalme de capa vegetal e 10 a 15 CMS de espesor por meios mecanicos. Incluye; acarreo dentro e la obra, equipo, herrramienta menor y mano de obra", null, null},
                {"1.2", null, null, null},
                {"1.3", null, null, null},
                {"1.4", null, null, null},
                {"1.5", null, null, null}
            },
            new String [] {
                "Clave", "Concepto", "Unidad", "P.U"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        pnlConceptosPre.add(jScrollPane3);

        pnlPreliminares.add(pnlConceptosPre, java.awt.BorderLayout.CENTER);

        pnlBotones.setLayout(new java.awt.BorderLayout());

        btnAgregarPreliminar.setText("+Agregar Conceptos");
        pnlBotones.add(btnAgregarPreliminar, java.awt.BorderLayout.EAST);

        pnlPreliminares.add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout pnlPrincipalPreliminaresLayout = new javax.swing.GroupLayout(pnlPrincipalPreliminares);
        pnlPrincipalPreliminares.setLayout(pnlPrincipalPreliminaresLayout);
        pnlPrincipalPreliminaresLayout.setHorizontalGroup(
            pnlPrincipalPreliminaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalPreliminaresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPreliminares, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPrincipalPreliminaresLayout.setVerticalGroup(
            pnlPrincipalPreliminaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalPreliminaresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPreliminares, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipalPreliminares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalPreliminares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Preeliminares dialog = new Preeliminares(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPreliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlConceptosPre;
    private javax.swing.JPanel pnlPreliminares;
    private javax.swing.JPanel pnlPrincipalPreliminares;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
