/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.arquitecto.frontend.dialog;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import com.arquitecto.frontend.components.BotonPrimario;
import com.arquitecto.frontend.components.PanelFondo;
import com.arquitecto.frontend.components.PanelSemitransparente;
import com.arquitecto.frontend.themes.Temas;
import org.springframework.beans.factory.annotation.Autowired;

@Component
@Scope("prototype")
public class NuevoProyecto extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NuevoProyecto.class.getName());

    /**
     * Creates new form NuevoProyecto
     */
    @Autowired
    public NuevoProyecto() {
        super( );
        
    }
    public void init(){
        initComponents();
        setModalityType(ModalityType.APPLICATION_MODAL);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new PanelFondo();
        PnlCabecera = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        pnllBotones = new javax.swing.JPanel();
        btnCancelar = new BotonPrimario(Temas.ROJO);
        btnCrear = new BotonPrimario(Temas.VERDE);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        PnlCabecera.setOpaque(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Agrega el nombre del Proyecto");
        PnlCabecera.add(lblTitulo);

        pnlPrincipal.add(PnlCabecera, java.awt.BorderLayout.NORTH);

        pnlCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 50, 50, 20));
        pnlCentro.setOpaque(false);
        pnlCentro.setLayout(new java.awt.GridLayout());
        pnlCentro.add(txtNombre);

        pnlPrincipal.add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnllBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnllBotones.setOpaque(false);
        pnllBotones.setLayout(new java.awt.BorderLayout());

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        pnllBotones.add(btnCancelar, java.awt.BorderLayout.WEST);

        btnCrear.setText("Crear");
        pnllBotones.add(btnCrear, java.awt.BorderLayout.EAST);

        pnlPrincipal.add(pnllBotones, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        this.dispose();;
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlCabecera;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnllBotones;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
