/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.arquitecto.frontend.dialog;

import com.arquitecto.frontend.editor.ButtonEditor;
import com.arquitecto.frontend.renders.ButtonRenderer;
import com.arquitecto.frontend.vista.VentanaPrincipal;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author Carlos Daniel
 */
@Component
@Scope("prototype")
public class Preeliminares extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Preeliminares.class.getName());
    
    @Autowired
    private VentanaPrincipal ventanaPrincipal;
    
    private boolean[] estados;
    
    @Autowired
    private ButtonRenderer buttonRenderer;  // ← Spring inyecta
    
    @Autowired
   private ButtonEditor buttonEditor; 

   
    @Autowired
    public Preeliminares() {
        super();
        
    }
    
    public void init(VentanaPrincipal parent, boolean[] estados) {
        this.ventanaPrincipal = parent;
        this.estados = estados;
        setModalityType(ModalityType.APPLICATION_MODAL);
        initComponents();
        prepararTabla();
        configurarBoton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalPreliminares = new javax.swing.JPanel();
        pnlPreliminares = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        pnlConceptosPre = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPreliminares = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        btnAgregarPreliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPreliminares.setLayout(new java.awt.BorderLayout());

        pnlTitulo.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        txtTitulo.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setText("Preeliminares");
        jPanel1.add(txtTitulo);

        pnlTitulo.add(jPanel1, java.awt.BorderLayout.NORTH);

        pnlPreliminares.add(pnlTitulo, java.awt.BorderLayout.NORTH);

        pnlConceptosPre.setLayout(new java.awt.GridLayout(1, 0));

        tblPreliminares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1.1", "Despalme de capa", "m3", "123", null},
                {"1.2", "Limpieza, trazo y eliminacion", "m2", "485", null},
                {"1.3", "Excavacion", "m3", "785", null},
                {"1.4", "Excavacion", "m3", "120", null},
                {"1.5", "Acarreo", "m3", "985", null}
            },
            new String [] {
                "Clave", "Concepto", "Unidad", "P.U", "Acciones"
            }
        ));
        tblPreliminares.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblPreliminares.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane3.setViewportView(tblPreliminares);

        pnlConceptosPre.add(jScrollPane3);

        pnlPreliminares.add(pnlConceptosPre, java.awt.BorderLayout.CENTER);

        pnlBotones.setLayout(new java.awt.BorderLayout());

        btnAgregarPreliminar.setText("Confirmar");
        btnAgregarPreliminar.addActionListener(this::btnAgregarPreliminarActionPerformed);
        pnlBotones.add(btnAgregarPreliminar, java.awt.BorderLayout.EAST);

        pnlPreliminares.add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout pnlPrincipalPreliminaresLayout = new javax.swing.GroupLayout(pnlPrincipalPreliminares);
        pnlPrincipalPreliminares.setLayout(pnlPrincipalPreliminaresLayout);
        pnlPrincipalPreliminaresLayout.setHorizontalGroup(
            pnlPrincipalPreliminaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalPreliminaresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPreliminares, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPrincipalPreliminaresLayout.setVerticalGroup(
            pnlPrincipalPreliminaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalPreliminaresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPreliminares, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipalPreliminares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalPreliminares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPreliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPreliminarActionPerformed
        this.dispose();
        
        
      
    }//GEN-LAST:event_btnAgregarPreliminarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPreliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlConceptosPre;
    private javax.swing.JPanel pnlPreliminares;
    private javax.swing.JPanel pnlPrincipalPreliminares;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTable tblPreliminares;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables

   
        public void prepararTablaPre(List<Integer> ids) {
    
        
    }

    private void prepararTabla() {
    DefaultTableModel model = (DefaultTableModel) tblPreliminares.getModel();
        
        // Por cada fila, poner el estado guardado
        for (int i = 0; i < model.getRowCount() && i < estados.length; i++) {
            // La columna "Acción" es la última
            int columnaAccion = model.getColumnCount() - 1;
            model.setValueAt(estados[i], i, columnaAccion);
    }
       
    }
    private void configurarBoton() {
        System.out.println("hola pituras");
    int columnaBoton = tblPreliminares.getColumnModel().getColumnIndex("Acciones");
    TableColumn columna = tblPreliminares.getColumnModel().getColumn(columnaBoton);
    
    columna.setCellRenderer(buttonRenderer);

    buttonEditor.init(tblPreliminares, estados);
    columna.setCellEditor(buttonEditor);
    
}
        
    
}
    

